# Exercício:

## 01 – Obtenha os resultados e retorne o código Python dos seguintes cálculos:

<br>a = 2.0 + 3.0 / 5.0 == 10
<br>b = (a + 10.2) - 5.0 * 2.0 <= 2.9
<br>c = 10 <= a / b + 33.8 < 100
<br>d = 5 != a / (b + c)
<br>e = 33 == d * 2

In [1]:
a = 2.0 + 3.0 / 5.0 == 10
b = (a + 10.2) - 5.0 * 2.0 <= 2.9
c = 10 <= a / b + 33.8 < 100
d = 5 != a / (b + c)
e = 33 == d * 2

print(a)
print(b)
print(c)
print(d)
print(e)

False
True
True
True
False


## 02 – Altere os operadores relacionais para modificar o resultado de cada uma das comparações.

<br>('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>['a',1,True,'b',0,False] > ['a',True,1]
<br>['a',1,True,'b',0,False] == 1
<br>['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [2]:
('a',1,True,'b',0,False) == ('a',True,1,'b',False,0)

True

In [3]:
['a',1,True,'b',0,False] == ('a',True,1,'b',False,0)

False

In [4]:
['a',1,True,'b',0,False] == ['a',True,1,'b',False,0]

True

In [5]:
['a',1,True,'b',0,False] < ['a',True,1]

False

In [6]:
['a',1,True,'b',0,False] != 1

True

In [7]:
['a',True,1] <= ['a',True,1] > ['a',1,True,'b',0,False]

False

## 03 – Usando o método DataFrame.to_csv(‘nome_do_arquivo.csv’) exporte o objeto obtido no exercício 10 da aula anterior para um arquivo CSV. Usando o método pd.read_csv(‘nome_do_arquivo.csv’) instancie uma DataFrame. Use o valor ‘Unnamed: 0’ no parâmetro index_col, para ajustar o index. Arredonde os valores para até três casas decimais, usando o método round().
Recupere a DataFrame.

In [9]:
import pandas as pd

In [11]:
df_ex3 = pd.read_csv('df_ex7.csv', index_col='Unnamed: 0').round(3)
df_ex3

,Coluna 1,Coluna 2,Coluna 3,Coluna 4,Médias
Linha 1,2.600,2.800,34.729,0.069,10.050
Linha 2,0.139,1.612,1.673,5.893,2.329
Linha 3,0.263,0.372,2.600,2.800,1.509
Linha 4,34.729,0.069,0.139,1.612,9.137
Linha 5,1.673,5.893,0.263,0.372,2.050
Médias,7.881,2.149,7.881,2.149,5.015


## 04 – Instancie um numpy array que apresente o mesmo formato (linhas e colunas) da DataFrame. Este array deve conter apenas inteiros uns.
Recupere o array.

Obs.: Procure na internet o método numpy.ones()

In [12]:
import numpy as np

In [14]:
array_uns = np.ones(df_ex3.shape)
array_uns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 05 – Quantos dos valores contidos na DataFrame são iguais aos valores no array?

In [15]:
df_ex3.values == array_uns

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

* R.: Nenhum valor é igual.

## 06 – Quantos dos valores contidos na DataFrame são superiores aos valores no array?

In [16]:
df_ex3.values > array_uns

array([[ True,  True,  True, False,  True],
       [False,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [ True, False, False,  True,  True],
       [ True,  True, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [17]:
(df_ex3.values > array_uns).sum()

np.int64(22)

* R.: 22 valores do data frame são maiores que no array.

## 07 – Quantos dos valores contidos na DataFrame são iguais ou inferiores aos valores no array?

In [19]:
df_ex3.values <= array_uns

array([[False, False, False,  True, False],
       [ True, False, False, False, False],
       [ True,  True, False, False, False],
       [False,  True,  True, False, False],
       [False, False,  True,  True, False],
       [False, False, False, False, False]])

In [20]:
(df_ex3.values <= array_uns).sum()

np.int64(8)

* R.: 8 valores do data frame são iguais ou inferiores ao do array de uns.

## 08 – Quantos dos valores contidos na DataFrame estão entre 0 e 1?

In [23]:
(df_ex3.values > 0) & (df_ex3.values < 1)

array([[False, False, False,  True, False],
       [ True, False, False, False, False],
       [ True,  True, False, False, False],
       [False,  True,  True, False, False],
       [False, False,  True,  True, False],
       [False, False, False, False, False]])

In [24]:
((df_ex3.values > 0) & (df_ex3.values < 1)).sum()

np.int64(8)

* R.: 8 valores na data frame estão entre 0 e 1.

## 09 – Quantos dos valores das médias das linhas são inferiores ou iguais à 5?

Obs 1.: Usando o método de classe, você pode converter qualquer objeto em outra classe. Ex. obj = list(array)

Obs 2.: Assim com o objeto da classe str, listas também possuem a função count()

In [25]:
df_ex3['Médias']

Linha 1    10.050
Linha 2     2.329
Linha 3     1.509
Linha 4     9.137
Linha 5     2.050
Médias      5.015
Name: Médias, dtype: float64

In [26]:
df_ex3['Médias'] <= 5

Linha 1    False
Linha 2     True
Linha 3     True
Linha 4    False
Linha 5     True
Médias     False
Name: Médias, dtype: bool

In [27]:
(df_ex3['Médias'] <= 5).sum()

np.int64(3)

* R.: 3 valores da coluna de "Médias das linhas" são menores ou iguais a 5.

## 10 – Quantos dos valores das médias das colunas são superiores à 5?

In [31]:
df_ex3.loc['Médias']

Coluna 1    7.881
Coluna 2    2.149
Coluna 3    7.881
Coluna 4    2.149
Médias      5.015
Name: Médias, dtype: float64

In [32]:
df_ex3.loc['Médias'] > 5

Coluna 1     True
Coluna 2    False
Coluna 3     True
Coluna 4    False
Médias       True
Name: Médias, dtype: bool

In [33]:
(df_ex3.loc['Médias'] > 5).sum()

np.int64(3)

* R.: 3 valores das médias das colunas são superiores a 5.